### PR TITLE
Separated attributes from public attributes in flags

### PR DESCRIPTION
**Pull request by mchan143**
Some of the attributes in the flags should not be public facing since they are not referenced outside of the object.

### CODE REVIEW

**Comment by unkempthenry** [comment]
Once https://github.com/mitre/training/pull/100 is merged, can you add the change that consolidates the flag loading ( https://github.com/mitre/training/pull/100/files#diff-8bc1f999d73f1bed9d24327079cfe700R73 ) to this PR ?

**Comment by mchan143** [comment]
In defining flags, flag_type should now be _flag_type instead.

Example for a fill in the blank flag type:
```
name = 'Fill in the Blank Question'
challenge = 'The opposite of up is _____'
answer = 'down'

_flag_type = 'fillinblank'
```

**Review by unkempthenry — APPROVED** [review]
@wbooth , this touches a lot of files, but simplifies the flag loading code in `hook.py`.  It would also impose that flag authors prefix variables that shouldn't be passed to the Flag constructors with a `_` .

**Review by wbooth — CHANGES_REQUESTED** [review]
move to flag object as discussed

**Comment by unkempthenry** [comment]
Marked this as a draft.  @mchan143 can either revive this PR, or create a new one now that we know the direction we want to go for flag definitions

**Pull request closed without merging**
